version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.code.gson:gson
  - dependency-name: com.google.guava:guava
  - dependency-name: org.apache.logging.log4j:log4j-core
  - dependency-name: "org.mockito:mockito-core"
    versions: ">= 5"
  - dependency-name: ch.jalu:configme
